Updates
git-svn-id: https://pegasus.isi.edu/svn/corral/trunk@1208 e217846f-e12e-0410-a4e5-89ccaea66ff7

diff --git a/service/libexec/glidein_install b/service/libexec/glidein_install
--- a/service/libexec/glidein_install
+++ b/service/libexec/glidein_install
@@ -1,44 +1,32 @@
 #!/bin/sh
 
-# Define my_exit function
-# We need to create a file that contains the return code of
-# this process because Condor-G can't retrieve the exit code of a
-# job submitted to GT2. So instead we write the exit code to a file
-# and transfer the file back to the submit machine where it can be
-# read to determine the true return code of the job. This is a
-# lightweight replacement for kickstart.
-O_WORK_DIR=`pwd` # Original work directory where rc file will be created
-echo "99 Unknown failure" > ${O_WORK_DIR}/rc
-my_exit ()
-{
-	rc=$1
-	msg=$2
-	echo $msg
-	# Exit code 1 is a parameter error
-	if [ "$rc" = "1" ]; then usage; fi
-	echo "$rc $msg" > ${O_WORK_DIR}/rc
-	exit $rc
-}
-
 # Usage
 CMD=`basename $0`
 usage ()
 {
-	echo """Usage: $CMD -installPath <path> [-version <version> | -package <tar.gz>] -url <url> [-url <url> ...]
+	echo """Usage: $CMD OPTIONS REQUIRED
 
+REQUIRED
+
+  -i | -installPath <path>
+      The path to install the Condor executables.
+  -v | -condorVersion <version>
+      The version of Condor to use. Ex: 7.0.0. Specify either -condorVersion
+      or -condorPackage, but not both.
+  -p | -condorPackage <tar.gz>
+      The tar.gz archive to download. Default is gathered from system info.
+      Ex: 7.0.0-x86-Linux-2.4-glibc2.3.tar.gz. Specify either -condorVersion
+      or -condorPackage, but not both.
+  -u | -url <url> ...
+      The server URL where the glidein jobs are hosted. Protocols supported
+      include: http, https, ftp, and gsiftp. Multiple -url arguments are
+      allowed.
+      
 OPTIONS
 
-  -installPath <path>
-      The path to install the Condor executables.
-  -version <version>
-      The version of Condor to use. Ex: 7.0.0
-  -package <tar.gz>
-      The tar.gz archive to download. Default is gathered from system info.
-      Ex: 7.0.0-x86-Linux-2.4-glibc2.3.tar.gz
-  -url <url>
-      The server URL where the glidein jobs are hosted. Protocols supported
-      include: http, https, ftp, and gsiftp.
-"""
+  -h | -help
+      Display this usage message
+""" >&2
 }
 
 SERVER_URLS=""
@@ -48,11 +36,12 @@ PACKAGE=""
 
 while [ $# -ge 1 ]; do
 	case $1 in
-		-installPath) INSTALL_PATH=$2 ;;
-		-version) VERSION=$2 ;;
-		-package) PACKAGE=$2 ;;
-		-url) SERVER_URLS="${SERVER_URLS} $2" ;;
-		*) my_exit 1 "Unknown argument: $1" ;;
+		-i | -installPath) INSTALL_PATH=$2 ;;
+		-v | -condorVersion) VERSION=$2 ;;
+		-p | -condorPackage) PACKAGE=$2 ;;
+		-u | -url) SERVER_URLS="${SERVER_URLS}$2 " ;;
+		-h | -help) usage ; exit 1 ;;
+		*) echo "Unknown argument: $1" >&2 ; exit 1 ;;
 	esac
 	shift
 	shift
@@ -60,38 +49,46 @@ done
 
 # Must specify path
 if [ -z "${INSTALL_PATH}" ]; then
-	my_exit 1 "Must specify -path"
+	echo "Must specify -installPath" >&2
+	exit 1
 fi
 if ! echo ${INSTALL_PATH} | grep -q -E "^/"; then
-	my_exit 1 "Invalid path ${INSTALL_PATH}"
+	echo "Install path must be absolute: ${INSTALL_PATH}" >&2
+	exit 1
 fi
 
 # Need at least one server url
 if [ -z "${SERVER_URLS}" ]; then
-	my_exit 1 "Must specify at least one -url"
+	echo "Must specify at least one -url" >&2
+	exit 1
 fi
 for URL in ${SERVER_URLS}; do
 	if ! echo $URL | grep -q -E "(^gsiftp)|(^http)|(^ftp)"; then
-		my_exit 1 "Invalid URL: $URL"
+		echo "Invalid URL: $URL" >&2
+		exit 1
 	fi
 done
 
 # Must specify either package or version
 if [ -z "$PACKAGE" ] && [ -z "$VERSION" ]; then
-	my_exit 1 "Must specify -package or -version"
+	echo "Must specify -condorPackage or -condorVersion" >&2
+	exit 1
 fi
 if [ ! -z "$PACKAGE" ] && [ ! -z "$VERSION" ]; then
-	my_exit 1 "Must specify either -package or -version"
+	echo "Must specify either -condorPackage or -condorVersion" >&2
+	exit 1
 fi
 if [ ! -z "$VERSION" ]; then
 	if ! echo $VERSION | grep -q -E "^[0-9]+[.][0-9]+[.][0-9]+$"; then
-		my_exit 1 "Invalid Condor version: $VERSION"
+		echo "Invalid Condor version: $VERSION" >&2
+		exit 1
 	fi
 fi
 
 # Check environment
 if [ -z "${GLOBUS_LOCATION}" ]; then
-	my_exit 2 "GLOBUS_LOCATION environment variable not set"
+	echo "GLOBUS_LOCATION environment variable not set" >&2
+	exit 1
 fi
 
 # If user specified version only, then determine package
@@ -181,7 +178,8 @@ fi
 PACKAGE_PATH=`pwd`/package.tar.gz
 GUC=${GLOBUS_LOCATION}/bin/globus-url-copy
 if [ ! -x $GUC ]; then
-	my_exit 2 "Unable to locate globus-url-copy"
+	echo "Unable to locate globus-url-copy" >&2
+	exit 1
 fi
 for URL in ${SERVER_URLS}; do
 	
@@ -210,22 +208,24 @@ done
 
 # If package could not be downloaded from any server
 if [ ! -f ${PACKAGE_PATH} ]; then
-	my_exit 3 "Failed to retrieve $PACKAGE"
+	echo "Failed to retrieve $PACKAGE" >&2
+	exit 1
 fi
 
 # Make install directory if it doesn't exist
 if [ ! -d ${INSTALL_PATH} ]; then
 	mkdir -p ${INSTALL_PATH}
 	if [ ! -d ${INSTALL_PATH} ]; then
-		my_exit 4 "Unable to create remote install directory: ${INSTALL_PATH}"
+		echo "Unable to create remote install directory: ${INSTALL_PATH}" >&2
+		exit 1
 	fi
 fi
 
 # Install package
 cd ${INSTALL_PATH}
 if ! tar -xzf ${PACKAGE_PATH}; then
-	my_exit 5 "Failed to install Condor glidein package"
+	echo "Failed to install Condor glidein package" >&2
+	exit 1
 fi
 
-# Exit successfully
-my_exit 0
+exit 0
diff --git a/service/libexec/glidein_run b/service/libexec/glidein_run
--- a/service/libexec/glidein_run
+++ b/service/libexec/glidein_run
@@ -4,30 +4,31 @@
 CMD=`basename $0`
 usage ()
 {
-	echo """Usage: $CMD -installPath <path> -localPath <path> 
-	                    -condorHost <host:port> -wallTime <minutes> OPTIONS
+	echo """Usage: $CMD OPTIONS REQUIRED
 
 REQUIRED
 
-  -installPath <path>
+   -i | -installPath <path>
       The path to install the Condor executables.
-   -localPath <path>
+   -l | -localPath <path>
       The path where log files should be written.
-   -condorHost <host:port>
+   -c | -condorHost <host:port>
       The condor central manager host.
-   -wallTime <minutes>
+   -t | -wallTime <minutes>
       The glidein runtime in minutes.
       
 OPTIONS
 
-   -idleTime <minutes>
+   -it | -idleTime <minutes>
       The maximum idle time for this glidein.
-   -debug <level> [-debug <level> ...]
+   -d | -debug <level> [-debug <level> ...]
       Turn on extra debugging messages and leave local directory in place.
-   -gcbBroker
+   -b | -gcbBroker
       The IP of the GCB broker for this glidein.
-   -numCpus
+   -n | -numCpus
       The number of CPUs to allocate for this glidein.
+   -h | -help
+      Display this usage message.
 """ >&2
 }
 
@@ -42,15 +43,16 @@ NUM_CPUS=""
 
 while [ $# -ge 1 ]; do
 	case $1 in 
-		-installPath) INSTALL_PATH=$2 ;;
-		-localPath) LOCAL_PATH=$2 ;;
-		-condorHost) CONDOR_HOST=$2 ;;
-		-wallTime) WALL_TIME=$2 ;;
-		-idleTime) IDLE_TIME=$2 ;;
-		-gcbBroker) GCB_BROKER=$2 ;;
-		-numCpus) NUM_CPUS=$2 ;;
-		-debug) DEBUG="${DEBUG}$2 " ;;
-		*) echo "Invalid argument: $1" >2 ; usage ;;
+		-i | -installPath) INSTALL_PATH=$2 ;;
+		-l | -localPath) LOCAL_PATH=$2 ;;
+		-c | -condorHost) CONDOR_HOST=$2 ;;
+		-t | -wallTime) WALL_TIME=$2 ;;
+		-it | -idleTime) IDLE_TIME=$2 ;;
+		-b | -gcbBroker) GCB_BROKER=$2 ;;
+		-n | -numCpus) NUM_CPUS=$2 ;;
+		-d | -debug) DEBUG="${DEBUG}$2 " ;;
+		-h | -help) usage ; exit 1 ;;
+		*) echo "Invalid argument: $1" >&2 ; exit 1 ;;
 	esac
 	shift
 	shift
@@ -59,22 +61,18 @@ done
 # Check arguments
 if [ -z "${INSTALL_PATH}" ]; then
 	echo "Must specify -installPath" >&2
-	usage
 	exit 1
 fi
 if [ -z "${LOCAL_PATH}" ]; then
 	echo "Must specify -localPath" >&2
-	usage
 	exit 1
 fi
 if [ -z "${CONDOR_HOST}" ]; then
 	echo "Must specify -condorHost" >&2
-	usage
 	exit 1
 fi
 if [ -z "${WALL_TIME}" ]; then
 	echo "Must specify -wallTime" >&2
-	usage
 	exit 1
 fi
 
diff --git a/service/libexec/glidein_uninstall b/service/libexec/glidein_uninstall
--- a/service/libexec/glidein_uninstall
+++ b/service/libexec/glidein_uninstall
@@ -1,56 +1,48 @@
 #!/bin/sh
 
-# Define my_exit function
-# We need to create a file that contains the return code of
-# this process because Condor-G can't retrieve the exit code of a
-# job submitted to GT2. So instead we write the exit code to a file
-# and transfer the file back to the submit machine where it can be
-# read to determine the true return code of the job. This is a
-# lightweight replacement for kickstart.
-O_WORK_DIR=`pwd` # Original work directory where rc file will be created
-echo "99 Unknown failure" > ${O_WORK_DIR}/rc
-my_exit ()
-{
-	rc=$1
-	msg=$2
-	echo $msg
-	# Exit code 1 is a parameter error
-	if [ "$rc" = "1" ]; then usage; fi
-	echo "$rc $msg" > ${O_WORK_DIR}/rc
-	exit $rc
-}
-
 # Usage
 CMD=`basename $0`
 usage ()
 {
-	echo """Usage: $CMD -installPath <path>
+	echo """Usage: $CMD OPTIONS REQUIRED
 
+REQUIRED
+
+  -i | -installPath <path>
+      The path to install the Condor executables.
+      
 OPTIONS
 
-  -installPath <path>
-      The path to install the Condor executables.
-"""
+  -h | -help
+      Display this usage message.
+""" >&2
 }
 
 INSTALL_PATH=""
 
 while [ $# -ge 1 ]; do
 	case $1 in
-		-installPath) INSTALL_PATH=$2 ;;
-		*) my_exit 1 "Invalid argument $1" ;;
+		-i | -installPath) INSTALL_PATH=$2 ;;
+		-h | -help) usage ; exit 1 ;;
+		*) echo "Invalid argument $1" >&2 ; exit 1 ;;
 	esac
 	shift
 	shift
 done
 
 if [ -z "${INSTALL_PATH}" ]; then
-	my_exit 1 "Missing -installPath"
+	echo "Missing -installPath" >&2
+	exit 1
 fi
 
 # Remove installation directory
 if [ -d ${INSTALL_PATH} ]; then
 	rm -rf ${INSTALL_PATH}
+	rc=$?
+	if [ $rc -ne 0 ]; then
+		echo "Unable to delete install directory: ${INSTALL_PATH}" >&2
+		exit 1
+	fi
 fi
 
-my_exit 0
+exit 0
