Prevent long error messages from gumming up list-sites or list-glideins output. All script errors are written to a status file now instead of stderr. This prevents messages like "Killed by signal 15" and "Added host XYZ to list of known hosts" from causing the glidein to fail.
git-svn-id: https://pegasus.isi.edu/svn/corral/trunk@1559 e217846f-e12e-0410-a4e5-89ccaea66ff7

diff --git a/share/glidein_install b/share/glidein_install
--- a/share/glidein_install
+++ b/share/glidein_install
@@ -1,10 +1,39 @@
 #!/bin/sh
+#
+# Copyright 2007-2009 University Of Southern California
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+# http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing,
+# software distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+# Create status file if not interactive
+if [ ! -t 0 ]; then
+	STATUS=`pwd`/status
+	touch $STATUS
+fi
+
+# Write error message to stderr and to status file if not interactive
+error ()
+{
+	echo "$@" >&2
+	if [ ! -t 0 ]; then
+		echo "$@" >>$STATUS
+	fi
+}
 
 # Usage
 CMD=`basename $0`
 usage ()
 {
-	echo """Usage: $CMD OPTIONS -i <path> (-v <version> | -p <package>)
+	error """Usage: $CMD OPTIONS -i <path> (-v <version> | -p <package>)
 
 OPTIONS
 
@@ -27,7 +56,7 @@ OPTIONS
 	  absolute path or URL.
   -h | -help
       Display this usage message
-""" >&2
+"""
 }
 
 # If we have GLOBUS_LOCATION, then source the env script
@@ -53,7 +82,7 @@ while [ $# -ge 1 ]; do
 		-p | -condorPackage) PACKAGE=$2 ;;
 		-r | -rls) RLS_URL=$2 ;;
 		-h | -help) usage ; exit 1 ;;
-		*) echo "Unknown argument: $1" >&2 ; exit 1 ;;
+		*) error "Unknown argument: $1" ; exit 1 ;;
 	esac
 	shift
 	shift
@@ -61,7 +90,7 @@ done
 
 # Must specify path
 if [ -z "${INSTALL_PATH}" ]; then
-	echo "Must specify -installPath" >&2
+	error "Must specify -installPath"
 	exit 1
 fi
 
@@ -70,20 +99,20 @@ INSTALL_PATH=`eval "echo ${INSTALL_PATH}"`
 
 # Make sure path is absolute
 if ! echo ${INSTALL_PATH} | grep -q -E "^/"; then
-	echo "Install path must be absolute: ${INSTALL_PATH}" >&2
+	error "Install path must be absolute: ${INSTALL_PATH}"
 	exit 1
 fi
 
 # Need either package or version
 if [ -z "${PACKAGE}" ] && [ -z "${VERSION}" ]; then
-	echo "Please specify either -condorPackage or -condorVersion" >&2
+	error "Please specify either -condorPackage or -condorVersion"
 	exit 1
 fi
 
 # Validate version
 if [ ! -z "$VERSION" ]; then
 	if ! echo "$VERSION" | grep -q -E "^[0-9]+[.][0-9]+[.][0-9]+$"; then
-		echo "Invalid Condor version: $VERSION" >&2
+		error "Invalid Condor version: $VERSION"
 		exit 1
 	fi
 fi
@@ -91,7 +120,7 @@ fi
 # Validate package name
 if [ ! -z "${PACKAGE}" ]; then
 	if ! echo "$PACKAGE" | grep -q -E ".tar.gz$"; then
-		echo "Condor package must be .tar.gz: $PACKAGE" >&2
+		error "Condor package must be .tar.gz: $PACKAGE"
 		exit 1
 	fi
 fi
@@ -192,7 +221,7 @@ if [ -z "${PACKAGE_URL}" ]; then
 
 	# Check to make sure we found globus-rls-cli
 	if [ ! -x $RLS ]; then
-		echo "Unable to locate globus-rls-cli" >&2
+		error "Unable to locate globus-rls-cli"
 		exit 1
 	fi
 
@@ -200,7 +229,7 @@ if [ -z "${PACKAGE_URL}" ]; then
 	RESULTS=`$RLS query lrc lfn $PACKAGE $RLS_URL`
 	rc=$?
 	if [ $rc != 0 ]; then
-		echo "Unable to get package URL from RLS" >&2
+		error "Unable to get package URL from RLS"
 		exit 1
 	fi
 	OLD_IFS=$IFS
@@ -239,7 +268,7 @@ for PACKAGE_URL in ${PACKAGE_URLS}; do
 		
 		# Check to make sure we have wget
 		if [ ! -x $WGET ]; then
-			echo "Unable to locate wget" >&2
+			error "Unable to locate wget"
 			exit 1
 		fi
 		
@@ -253,7 +282,7 @@ for PACKAGE_URL in ${PACKAGE_URLS}; do
 		
 		# Check to make sure we have globus-url-copy
 		if [ ! -x $GUC ]; then
-			echo "Unable to locate globus-url-copy" >&2
+			error "Unable to locate globus-url-copy"
 			exit 1
 		fi
 
@@ -275,7 +304,7 @@ done
 
 # If package could not be downloaded from any server
 if [ ! -f ${PACKAGE_PATH} ]; then
-	echo "Failed to retrieve binary worker package" >&2
+	error "Failed to retrieve binary worker package"
 	exit 1
 fi
 
@@ -283,7 +312,7 @@ fi
 if [ ! -d ${INSTALL_PATH} ]; then
 	mkdir -p ${INSTALL_PATH}
 	if [ ! -d ${INSTALL_PATH} ]; then
-		echo "Unable to create remote install directory: ${INSTALL_PATH}" >&2
+		error "Unable to create remote install directory: ${INSTALL_PATH}"
 		exit 1
 	fi
 fi
@@ -291,7 +320,7 @@ fi
 # Install package
 cd ${INSTALL_PATH}
 if ! tar -xzf ${PACKAGE_PATH}; then
-	echo "Failed to install Condor glidein package" >&2
+	error "Failed to install Condor glidein package"
 	exit 1
 fi
 
diff --git a/share/glidein_run b/share/glidein_run
--- a/share/glidein_run
+++ b/share/glidein_run
@@ -1,10 +1,39 @@
 #!/bin/sh
+#
+# Copyright 2007-2009 University Of Southern California
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+# http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing,
+# software distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+ 
+# Create status file if not interactive
+if [ ! -t 0 ]; then
+	STATUS=`pwd`/status
+	touch $STATUS
+fi
+
+# Write error message to stderr and to status file if not interactive
+error ()
+{
+	echo "$@" >&2
+	if [ ! -t 0 ]; then
+		echo "$@" >>$STATUS
+	fi
+}
 
 # Usage
 CMD=`basename $0`
 usage ()
 {
-	echo """Usage: $CMD OPTIONS REQUIRED
+	error """Usage: $CMD OPTIONS REQUIRED
 
 REQUIRED
 
@@ -31,7 +60,7 @@ OPTIONS
       The number of CPUs to allocate for this glidein.
    -h | -help
       Display this usage message.
-""" >&2
+"""
 }
 
 INSTALL_PATH=""
@@ -43,6 +72,7 @@ DEBUG=""
 GCB_BROKER=""
 NUM_CPUS=""
 SITE_NAME=""
+JOB_DIR="`dirname $X509_USER_PROXY 2>/dev/null || pwd`"
 
 while [ $# -ge 1 ]; do
 	case $1 in 
@@ -56,7 +86,7 @@ while [ $# -ge 1 ]; do
 		-d | -debug) DEBUG="${DEBUG}$2 " ;;
 		-s | -site) SITE_NAME=$2 ;;
 		-h | -help) usage ; exit 1 ;;
-		*) echo "Invalid argument: $1" >&2 ; exit 1 ;;
+		*) error "Invalid argument: $1" ; exit 1 ;;
 	esac
 	shift
 	shift
@@ -64,23 +94,23 @@ done
 
 # Check arguments
 if [ -z "${INSTALL_PATH}" ]; then
-	echo "Must specify -installPath" >&2
+	error "Must specify -installPath"
 	exit 1
 fi
 INSTALL_PATH=`eval "echo ${INSTALL_PATH}"`
 
 if [ -z "${LOCAL_PATH}" ]; then
-	echo "Must specify -localPath" >&2
+	error "Must specify -localPath"
 	exit 1
 fi
 LOCAL_PATH=`eval "echo ${LOCAL_PATH}"`
 
 if [ -z "${CONDOR_HOST}" ]; then
-	echo "Must specify -condorHost" >&2
+	error "Must specify -condorHost"
 	exit 1
 fi
 if [ -z "${WALL_TIME}" ]; then
-	echo "Must specify -wallTime" >&2
+	error "Must specify -wallTime"
 	exit 1
 fi
 
@@ -100,14 +130,14 @@ fi
 
 # Check install path
 if [ ! -d "${INSTALL_PATH}" ]; then
-	echo "Install path does not exist: ${INSTALL_PATH}" >&2
+	error "Install path does not exist: ${INSTALL_PATH}"
 	exit 1
 fi
 
 # Create local path if it doesn't exist
 if [ ! -d "${LOCAL_PATH}" ]; then
 	if ! mkdir -p ${LOCAL_PATH}; then
-		echo "Unable to create local dir: ${LOCAL_PATH}" >&2
+		error "Unable to create local dir: ${LOCAL_PATH}"
 		exit 1
 	fi
 fi
@@ -115,7 +145,7 @@ fi
 # Set condor config file
 GLIDEIN_CONDOR_CONFIG=`pwd`/glidein_condor_config
 if [ ! -f "${GLIDEIN_CONDOR_CONFIG}" ]; then
-	echo "Configuration file 'glidein_condor_config' missing" >&2
+	error "Configuration file 'glidein_condor_config' missing"
 	exit 1
 fi
 
@@ -130,23 +160,23 @@ esac
 # Set local directory
 LOCAL_DIR="${LOCAL_PATH}/${HOSTNAME}_$$"
 if ! mkdir -p ${LOCAL_DIR}; then
-	echo "Unable to create glidein local dir: ${LOCAL_DIR}" >&2
+	error "Unable to create glidein local dir: ${LOCAL_DIR}"
 	exit 1
 fi
 
 # Copy config file
 if ! cp ${GLIDEIN_CONDOR_CONFIG} ${LOCAL_DIR}; then
-	echo "Unable to copy glidein_condor_config to ${LOCAL_DIR}" >&2
+	error "Unable to copy glidein_condor_config to ${LOCAL_DIR}"
 	exit 1
 fi
 
 # Create log and execute dirs
 if ! mkdir -p ${LOCAL_DIR}/log; then
-	echo "Unable to create log dir: ${LOCAL_DIR}/log" >&2
+	error "Unable to create log dir: ${LOCAL_DIR}/log"
 	exit 1
 fi
 if ! mkdir -p ${LOCAL_DIR}/execute; then
-	echo "Unable to create execute dir: ${LOCAL_DIR}/execute" >&2
+	error "Unable to create execute dir: ${LOCAL_DIR}/execute"
 	exit 1
 fi
 
@@ -176,10 +206,17 @@ for ip in ${ips}; do
  		IP_ADDR=$ip
 	fi
 done
+if [ -z "${IP_ADDR}" ]; then
+	error "Unable to determine IP address for $HOSTNAME"
+	exit 1
+fi
 
 # Create lock dir
 GLIDEIN_LOCK=/tmp/glidein/lock
-mkdir -p $GLIDEIN_LOCK
+if ! mkdir -p $GLIDEIN_LOCK; then
+	error "Unable to create lock dir: $GLIDEIN_LOCK"
+	exit 1
+fi
 
 # Add condor config entries
 printf "\n\n" >> ${CONDOR_CONFIG}
@@ -237,8 +274,8 @@ while [ true ]; do
 		exit 0
 	fi
 	
-	# Did the job get killed? (i.e. did the scratch dir go away?)
-	if [ ! -d "$SCRATCH_DIRECTORY" ]; then
+	# Did the job get killed? (i.e. did the job dir go away?)
+	if [ ! -d "$JOB_DIR" ]; then
 		# Then kill the condor_master
 		kill $MPID
 	fi
diff --git a/share/glidein_uninstall b/share/glidein_uninstall
--- a/share/glidein_uninstall
+++ b/share/glidein_uninstall
@@ -1,10 +1,39 @@
 #!/bin/sh
+#
+# Copyright 2007-2009 University Of Southern California
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+# http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing,
+# software distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+# Create status file if not interactive
+if [ ! -t 0 ]; then
+	STATUS=`pwd`/status
+	touch $STATUS
+fi
+
+# Write error message to stderr and to status file if not interactive
+error ()
+{
+	echo "$@" >&2
+	if [ ! -t 0 ]; then
+		echo "$@" >>$STATUS
+	fi
+}
 
 # Usage
 CMD=`basename $0`
 usage ()
 {
-	echo """Usage: $CMD OPTIONS REQUIRED
+	error """Usage: $CMD OPTIONS REQUIRED
 
 REQUIRED
 
@@ -17,7 +46,7 @@ OPTIONS
 
   -h | -help
       Display this usage message.
-""" >&2
+"""
 }
 
 INSTALL_PATH=""
@@ -27,7 +56,7 @@ while [ $# -ge 1 ]; do
 		-i | -installPath) INSTALL_PATH=$2 ;;
 		-l | -localPath) LOCAL_PATH=$2 ;;
 		-h | -help) usage ; exit 1 ;;
-		*) echo "Invalid argument $1" >&2 ; exit 1 ;;
+		*) error "Invalid argument $1" ; exit 1 ;;
 	esac
 	shift
 	shift
@@ -35,13 +64,13 @@ done
 
 # Check arguments
 if [ -z "${INSTALL_PATH}" ]; then
-	echo "Missing -installPath" >&2
+	error "Missing -installPath"
 	exit 1
 fi
 INSTALL_PATH=`eval "echo ${INSTALL_PATH}"`
 
 if [ -z "${LOCAL_PATH}" ]; then
-	echo "Missing -localPath" >&2
+	error "Missing -localPath"
 	exit 1
 fi
 LOCAL_PATH=`eval "echo ${LOCAL_PATH}"`
@@ -51,7 +80,7 @@ if [ -d ${INSTALL_PATH} ]; then
 	rm -rf ${INSTALL_PATH}
 	rc=$?
 	if [ $rc -ne 0 ]; then
-		echo "Unable to delete install directory: ${INSTALL_PATH}" >&2
+		error "Unable to delete install directory: ${INSTALL_PATH}"
 		exit 1
 	fi
 fi
