Also delete localPath when removing site
git-svn-id: https://pegasus.isi.edu/svn/corral/trunk@1531 e217846f-e12e-0410-a4e5-89ccaea66ff7

diff --git a/share/glidein_uninstall b/share/glidein_uninstall
--- a/share/glidein_uninstall
+++ b/share/glidein_uninstall
@@ -10,6 +10,8 @@ REQUIRED
 
   -i | -installPath <path>
       The path where the Condor executables are installed.
+  -l | -localPath <path>
+      The path where log files have been written.
       
 OPTIONS
 
@@ -23,6 +25,7 @@ INSTALL_PATH=""
 while [ $# -ge 1 ]; do
 	case $1 in
 		-i | -installPath) INSTALL_PATH=$2 ;;
+		-l | -localPath) LOCAL_PATH=$2 ;;
 		-h | -help) usage ; exit 1 ;;
 		*) echo "Invalid argument $1" >&2 ; exit 1 ;;
 	esac
@@ -30,8 +33,13 @@ while [ $# -ge 1 ]; do
 	shift
 done
 
+# Check arguments
 if [ -z "${INSTALL_PATH}" ]; then
 	echo "Missing -installPath" >&2
+	exit 1
+fi
+if [ -z "${LOCAL_PATH}" ]; then
+	echo "Missing -localPath" >&2
 	exit 1
 fi
 
@@ -43,6 +51,13 @@ if [ -d ${INSTALL_PATH} ]; then
 		echo "Unable to delete install directory: ${INSTALL_PATH}" >&2
 		exit 1
 	fi
+fi
+
+# Remove log directory if it exists
+if [ -d ${LOCAL_PATH} ]; then
+	rm -rf ${LOCAL_PATH}
+	# The local path may be local to each node, so we may not
+	# be able to delete it here
 fi
 
 exit 0
